name: Main Config
version: 1.0.0
schema: v1

models:
  - name: ASU Qwen3 Coder
    provider: openai
    model: qwen36-35b-a3b
    apiBase: https://openai.rc.asu.edu/v1
    apiKey: ${{ secrets.OPENAI_API_KEY }}
    roles:
      - chat
      - edit
      - apply

  - name: ASU Muse Glimmer
    provider: openai
    model: muse-glimmer-30b
    apiBase: https://openai.rc.asu.edu/v1
    apiKey: ${{ secrets.OPENAI_API_KEY }}
    roles:
      - chat
      - edit
      - apply

  - name: ASU Devstral
    provider: openai
    model: devstral2-123b
    apiBase: https://openai.rc.asu.edu/v1
    apiKey: ${{ secrets.OPENAI_API_KEY }}
    roles:
      - chat
      - edit
      - apply
